### ISSUE TITLE
Project Two Feedback

### ISSUE THREAD

**Issue by ajhofferber** [carrafa/RESTaurant#1]
Hey Josh,

Really great job on this!  It seems to me like you were really thoughtful about interface and what made sense for this type of application... it feels like something a restaurant would actually use.  The responsive design of your application is great! I like how the layout of information changes based on screen size... makes sense to me! I thought that the 'orders/history' page for admin and the ingredients list for each item were really nice features as well.

Your code is really well organized and your markdown does a nice job of presenting your app to those who happen to find themselves on your github. The only thing I want to mention is that when I am in your parties/:id/bill page and I used the dropdown menu to select a tip, it directs me back to the parties/:id page instead of back to the bill. Not sure if it is supposed to do that of if it is a bug... just thought I'd point it out! Also, in your code, It looks like your currency converter should say USD and EURO, but the app online only says USD. Could just be me... but just pointing it out!

Overall, I think you have a really great finished product here. Nice work!

**Comment by carrafa** [comment]
Thanks Ash!

I fixed the tip bug, thanks for pointing that out.

That was weird about the currency bug.  I was using .toggle() and on my local server it was working fine.  Not sure why it wasn't working on heroku.  I just switched it to use .css() and it seems to be working fine on heroku now.

Thanks!

**Comment by ajhofferber** [comment]
Nice! :raised_hands: :raised_hands: :raised_hands: 

Also, I realize I didn't give you a score... and because grades matter SO much in this program, I am following up to tell you that you've received a 3 on this project! :100: :+1:
